### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by kaarelnu** [automatweb/automatweb_sales#1]
Kas default assigned saab ka panna?

**Comment by allaserik** [comment]
sain kirja ;)

2011/5/17 kaarelnu <
reply@reply.github.com>

> Kas default assigned saab ka panna?
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/automatweb/automatweb_sales/issues/1

## 

Parimatega,
Erik Allas
+372 55 588 309
SkypeMe @ allaserik

twitter.com/allaserik

**Comment by rainviigipuu** [comment]
Mina sain mingitel asjaoludel github-i notici.
